#pragma once

#define SERVER_PLAYER_CONNECTED 0
#define CLIENT_PLAYER_MOVED 1
#define SERVER_PLAYER_MOVED 2
#define SERVER_PLAYER_DISCONNECTED 3
#define CLIENT_CONNECTED 4
#define CLIENT_CHAT 5
#define SERVER_CHAT 6
#define CLIENT_MELEE_UPDATE 7
#define SERVER_MELEE_UPDATE 8